/*
 * Copyright 2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MIMX8DL1xxxFZ
package_id: MIMX8DL1AVNFZ
mcu_data: ksdk2_0
processor_version: 0.8.0
board: MIMX8DXL-EVK
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "pin_mux.h"
#include "fsl_common.h"
#include "main/imx8dxl_pads.h"
#include "svc/pad/pad_api.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUartPins:
- options: {callFromInitBoot: 'false', coreID: m4}
- pin_list:
  - {pin_num: AM34, peripheral: ADMA__UART0, signal: uart_rx, pin_signal: UART0_RX}
  - {pin_num: AN35, peripheral: ADMA__UART0, signal: uart_tx, pin_signal: UART0_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUartPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUartPins(sc_ipc_t ipc)                      /*!< Function assigned for the core: Cortex-M4F[m4] */
{
  sc_err_t err = SC_ERR_NONE;

  err = sc_pad_set_all(ipc, BOARD_INITUARTPINS_UART0_RX_PIN_FUNCTION_ID, 0U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_UART0_RX register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITUARTPINS_UART0_TX_PIN_FUNCTION_ID, 0U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_UART0_TX register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLcdPins:
- options: {callFromInitBoot: 'false', coreID: m4}
- pin_list:
  - {pin_num: V34, peripheral: ADMA__LCDIF, signal: lcdif_clk, pin_signal: MCLK_OUT0}
  - {pin_num: U35, peripheral: ADMA__LCDIF, signal: lcdif_en, pin_signal: MCLK_IN1}
  - {pin_num: T34, peripheral: ADMA__LCDIF, signal: lcdif_hsync, pin_signal: SPI3_CS0}
  - {pin_num: U33, peripheral: ADMA__LCDIF, signal: lcdif_vsync, pin_signal: MCLK_IN0}
  - {pin_num: P34, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 00', pin_signal: SPI3_SCK}
  - {pin_num: R35, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 01', pin_signal: SPI3_SDO}
  - {pin_num: R33, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 02', pin_signal: SPI3_SDI}
  - {pin_num: L33, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 03', pin_signal: ENET1_RGMII_TXD3}
  - {pin_num: W35, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 04', pin_signal: UART1_TX}
  - {pin_num: W33, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 05', pin_signal: UART1_RX}
  - {pin_num: W29, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 06', pin_signal: UART1_RTS_B}
  - {pin_num: AA29, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 07', pin_signal: UART1_CTS_B}
  - {pin_num: Y34, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 08', pin_signal: SPI0_SCK}
  - {pin_num: AA33, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 09', pin_signal: SPI0_SDI}
  - {pin_num: AA35, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 10', pin_signal: SPI0_SDO}
  - {pin_num: AC35, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 11', pin_signal: SPI0_CS1}
  - {pin_num: AB34, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 12', pin_signal: SPI0_CS0}
  - {pin_num: AE35, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 13', pin_signal: ADC_IN1}
  - {pin_num: AD34, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 14', pin_signal: ADC_IN0}
  - {pin_num: AF34, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 15', pin_signal: ADC_IN3}
  - {pin_num: AC33, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 16', pin_signal: ADC_IN2}
  - {pin_num: AG35, peripheral: ADMA__LCDIF, signal: 'lcdif_d, 17', pin_signal: ADC_IN5}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLcdPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLcdPins(sc_ipc_t ipc)                       /*!< Function assigned for the core: Cortex-M4F[m4] */
{
  sc_err_t err = SC_ERR_NONE;

  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_LCD_14_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_ADC_IN0 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_LCD_13_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_ADC_IN1 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_ADC_IN2_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_ADC_IN2 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_ADC_IN3_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_ADC_IN3 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_LCD_17_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_ADC_IN5 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_ENET1_RGMII_TXD3_PIN_FUNCTION_ID, 2U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_ENET1_RGMII_TXD3 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_LCD_VSYNC_PIN_FUNCTION_ID, 2U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_MCLK_IN0 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_LCD_03_PIN_FUNCTION_ID, 2U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_MCLK_IN1 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_LCD_CLK_PIN_FUNCTION_ID, 2U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_MCLK_OUT0 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI0_CS0_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI0_CS0 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI0_CS1_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI0_CS1 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI0_SCK_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI0_SCK register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI0_SDI_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI0_SDI register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI0_SDO_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI0_SDO register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI3_CS0_PIN_FUNCTION_ID, 2U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI3_CS0 register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI3_SCK_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI3_SCK register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI3_SDI_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI3_SDI register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_SPI3_SDO_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI3_SDO register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_UART1_CTS_B_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_UART1_CTS_B register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_UART1_RTS_B_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_UART1_RTS_B register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_UART1_RX_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_UART1_RX register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITLCDPINS_UART1_TX_PIN_FUNCTION_ID, 5U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_UART1_TX register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitIOExpanderI2CPins:
- options: {callFromInitBoot: 'false', coreID: m4}
- pin_list:
  - {pin_num: AP16, peripheral: ADMA__I2C2, signal: i2c_sda, pin_signal: SPI1_SCK}
  - {pin_num: AR17, peripheral: ADMA__I2C2, signal: i2c_scl, pin_signal: SPI1_SDO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitIOExpanderI2CPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitIOExpanderI2CPins(sc_ipc_t ipc)             /*!< Function assigned for the core: Cortex-M4F[m4] */
{
  sc_err_t err = SC_ERR_NONE;

  err = sc_pad_set_all(ipc, BOARD_INITIOEXPANDERI2CPINS_I2C2_SDA_PIN_FUNCTION_ID, 2U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI1_SCK register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITIOEXPANDERI2CPINS_I2C2_SCL_PIN_FUNCTION_ID, 2U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x40 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_SPI1_SDO register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
